[global]
log_level = 'info'
[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'akashnet-2'
type = 'CosmosSdk'
rpc_addr = 'https://rpc-akash.ecostake.com/'
websocket_addr = 'wss://rpc-akash.ecostake.com/websocket'
grpc_addr = 'https://akash-grpc.lavenderfive.com/'
rpc_timeout = '10s'
account_prefix = 'akash'
key_name = 'keyakash'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = '5s'
max_block_time = '30s'
memo_prefix = ''
sequential_batch_tx = false

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 0.1
denom = 'uakt'

[chains.packet_filter]
policy = 'allow'
list = [[
    'transfer',
    'channel-35',
]]

[chains.address_type]
derivation = 'cosmos'

[[chains]]
id = 'juno-1'
type = 'CosmosSdk'
rpc_addr = 'http://rpc-juno.freshstaking.com:39657/'
websocket_addr = 'ws://rpc-juno.freshstaking.com:39657/websocket'
grpc_addr = 'https://juno-grpc.lavenderfive.com/'
rpc_timeout = '10s'
account_prefix = 'juno'
key_name = 'keyjuno'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = '5s'
max_block_time = '30s'
memo_prefix = ''
sequential_batch_tx = false

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 0.1
denom = 'ujuno'

[chains.packet_filter]
policy = 'allow'
list = [[
    'transfer',
    'channel-29',
]]

[chains.address_type]
derivation = 'cosmos'

