[global]
log_level = 'trace'
[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'juno-1'
type = 'CosmosSdk'
rpc_addr = 'https://juno-rpc.polkachu.com/'
websocket_addr = 'wss://rpc.juno.kingnodes.com/websocket'
grpc_addr = 'https://juno-grpc.lavenderfive.com/'
rpc_timeout = '10s'
account_prefix = 'juno'
key_name = 'keyjuno'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 800000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = '5s'
max_block_time = '30s'
memo_prefix = ''
sequential_batch_tx = false

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 0.1
denom = 'ujuno'

[chains.packet_filter]
policy = 'allowall'

[chains.address_type]
derivation = 'cosmos'

[[chains]]
id = 'umee-1'
type = 'CosmosSdk'
rpc_addr = 'http://rpc-umee-0.node75.org:26657/'
websocket_addr = 'ws://rpc-umee-0.node75.org:26657/websocket'
grpc_addr = 'https://grpc-umee-ia.cosmosia.notional.ventures/'
rpc_timeout = '10s'
account_prefix = 'umee'
key_name = 'keyumee'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 800000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = '5s'
max_block_time = '30s'
memo_prefix = ''
sequential_batch_tx = false

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 0.1
denom = 'uumee'

[chains.packet_filter]
policy = 'allowall'

[chains.address_type]
derivation = 'cosmos'

